version: '2.2'

services:
  tb-js-executor:
    env_file:
      - queue-rabbitmq.env
  tb-core1:
    env_file:
      - queue-rabbitmq.env
    depends_on:
      - zookeeper
      - redis
  tb-core2:
    env_file:
      - queue-rabbitmq.env
    depends_on:
      - zookeeper
      - redis
  tb-rule-engine1:
    env_file:
      - queue-rabbitmq.env
    depends_on:
      - zookeeper
      - redis
  tb-rule-engine2:
    env_file:
      - queue-rabbitmq.env
    depends_on:
      - zookeeper
      - redis
  tb-mqtt-transport1:
    env_file:
      - queue-rabbitmq.env
    depends_on:
      - zookeeper
  tb-mqtt-transport2:
    env_file:
      - queue-rabbitmq.env
    depends_on:
      - zookeeper
  tb-http-transport1:
    env_file:
      - queue-rabbitmq.env
    depends_on:
      - zookeeper
  tb-http-transport2:
    env_file:
      - queue-rabbitmq.env
    depends_on:
      - zookeeper
  tb-coap-transport:
    env_file:
      - queue-rabbitmq.env
    depends_on:
      - zookeeper